config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "students#landing_page"
  # root to: "devise/sessions#new"
  get "/selected/:choose_course", to: "students#landing_page"
  get "/student/new", to: "students#new"
  get "/student/index", to: "students#index"
  post "/student/create", to: "students#create"
  get "/student/:id", to: "students#show", as: "student_show"
  get "/student/:id/edit", to: "students#edit", as: "student_edit"
  put "/student/:id/update", to: "students#update", as: "student_update"
  delete "/student/:id", to: "students#destroy", as: "student_delete"

  # Routes for Course Model
  # get "/course/new", to: "courses#new"
  # get "/course/index", to: "courses#index"
  # post "/course/create", to: "courses#create"
  # get "/course/:id", to: "courses#show", as: "course_show"
  # get "/course/:id/edit", to: "courses#edit", as: "course_edit"
  # put "/course/:id/update", to: "courses#update", as: "course_update"
  # delete "/course/:id", to: "courses#destroy", as: "course_delete"

  #Association Routes
  get "/student/:id/course/index", to: "courses#index", as: "student_id_course_index"
  post "course_buy", to: "courses#course_buy"
  get "/student/:id/courses", to: "students#student_courses", as: "student_courses"
  delete "/student/:id/courses", to: "students#student_delete_course", as: "student_delete_course"

  resources :courses do
    resources :payments, only: [:show, :index, :new, :create]  # Nest payments under courses
  end

  resources :lectures

  # resources :payments

  resources :contents

  resources :categories
  
  # root "home#index"

  # Defines the root path route ("/")
  # root "articles#index"
  get "/*path", to: "homes#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :profile_image       
    # validates :studFName, presence: true
    has_many :teachers 
    has_many :courses , through: :teachers

    # validates :studFName, :studLName, :yearOfEnroll , presence: true
    # validates :studFName, :studLName, length: {minimum: 2, maximum: 10}
    # validates :studPhone, presence: true, numericality: true

    # after_commit :display_student_created

    def display_student_created
      if self.studFName.present?
        puts "========= New User has been created!============"
      else
        puts "============== User is still not created, Some errors has been ocurred!========="  
      end
    end  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :set_student, only: [:edit,:show, :update, :destroy, :student_courses]

    helper_method :filter_course

    def landing_page
        @course = Course.all
        if params[:choose_course]
            @courses = filter_course(params[:choose_course])
        else
            @courses = filter_course("python")
        end
    end
    
    def new
        @student = Student.new
    end

    def index
        @student = Student.all
    end

    def selected
        
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            redirect_to student_index_path
        else 
            render :new
        end
    end

    def show
        # @student = Student.find(params[:id])
    end

    def edit
        # @student = Student.find(params[:id])
    end

    def update
        if @student.update(student_params)
            redirect_to student_show_path
        else
            # debugger
            # puts(@student.errors.full_messages)
            flash[:notice] = @student.errors.full_messages
            redirect_to student_edit_path
            # render plain: "student not found!"
        end
    end

    def destroy
        @student.destroy
        redirect_to student_index_path
    end

    def student_courses
        @all_courses = @student.courses
    end
    
    def student_delete_course
        @student = Student.find(params[:student_id]) 
        @course = Course.find(params[:course_id]) 
        @student.courses.delete(@course.id)

        redirect_to student_courses_path
    end

    def filter_course(req_course = "Python")
        @course = Course.all
        @newCourse = Array.new();
        @course.each do |course|
            if course.courseTitle.downcase.include? req_course.downcase
                @newCourse.push(course);
            end
        end
        
        return @newCourse;
    end

    private

    def student_params
        params.require(:student).permit(:studFName, :studMName, :studLName, :studAddressCity, :studPhone, :studGender, :yearOfEnroll, :profile_image)
    end

    def set_student
        @student = Student.find(params[:id])
    end

end

app/views/students/_form.html.erb
<%= form_with model: student, url: url, multipart: true, method: method  do |form| %>
  
    <% if student.errors.any? %>
        <div class="col-lg-12">
        <p>Please fix errors below:</p>
        <% student.errors.full_messages.each do |message|%>
            <p class="text-danger"><%= message%><p>
        <%end%>
    <%end%>

  <div class="mb-3">
    <%= form.label "First Name"%>
    <%= form.text_field :studFName, class: "form-control", placeholder: "First Name"%>
  </div>
  <div class="mb-3">
    <%= form.label "Middel Name"%>
    <%= form.text_field :studMName, class: "form-control", placeholder: "Middle Name"%>
  </div>
  <div class="mb-3">
    <%= form.label "Last Name"%>
    <%= form.text_field :studLName, class: "form-control", placeholder: "Last Name"%>
  </div>
  <div class="mb-3">
    <%= form.label "Address City"%>
    <%= form.text_field :studAddressCity, class: "form-control", placeholder: "City"%>
  </div>
  <div class="mb-3">
    <%= form.label "phone Number"%>
    <%= form.number_field :studPhone, class: "form-control", placeholder: "Phone Number"%>
  </div>
  <div class="mb-3">
    <label>Gender</label>
    <div class="form-check">
      <%= form.radio_button :studGender, 'Male', class: "form-check-input" %>
      <%= form.label :studGender_male, class: "form-check-label" do %>
        Male
      <% end %>
    </div>
    <div class="form-check">
      <%= form.radio_button :studGender, 'Female', class: "form-check-input" %>
      <%= form.label :studGender_female, class: "form-check-label" do %>
        Female
      <% end %>
    </div>
  </div>
  <div class="mb-3">
    <%= form.label "Year of Enroll"%>
    <%= form.datetime_field :yearOfEnroll, class: "form-control", placeholder: "Year"%>
  </div>
  <div class="mb-3">
    <%= form.label "Upload Image"%>
    <%= form.file_field :profile_image, class: "form-control"%>
  </div>
  <div class="mb-3">
    <%= form.submit "ADD", class: "btn btn-primary"%>
  </div>
<%end%>

app/views/students/edit.html.erb
<div class="nav">
  <h1>Update Student Profile</h1>
</div>
<%= render partial: "form", locals: {student: @student, url: student_update_path, method: :put }%>

app/views/students/index.html.erb
<%= stylesheet_link_tag('student_index') %>
<div class="nav">

  <h1>Student Dashboard</h1>
</div>
<div class="row">
  <% @student.each do |student|%>
    <div class="col-4 card">
      <div class="text">
        <a class="row title" href="/student/<%= student.id %>">
          <h3><%= student.id %></h3>
        </a>
        <div class="row">
          <p class="article"><%= student.studFName %> <%= student.studMName %> <%= student.studLName %></p>
          <p class="article">Address- <%= student.studAddressCity %></p>
          <p class="article">Gender- <%= student.studGender %> </p>
          <p class="article">Enrolled- <%= student.yearOfEnroll %> </p>
        </div>
        <div class="access-link">
          <a class="row link-opacity-100" href="/student/<%= student.id %>/course/index">
            <p>Buy course</p>
          </a>
          <a class="row link-opacity-100" href="/student/<%= student.id %>/courses">
            <p>Show all course</p>
          </a>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/students/landing_page.html.erb
<div class="container">
  <%# <img alt="udemy" src="/assets/images/udemy.jpg" /> %>
  
  <%= image_tag("udemy.jpg")%>
</div>
<div class="brands">
  <div class="container brand-logo">
    <div class="brand-text">Trusted by over 14,400 companies and millions of learners around the world</div>
    <div class="img-logo">
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/volkswagen.svg")%></div>
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/samsung.svg")%></div>
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/cisco.svg")%></div>
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/att.svg")%></div>
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/procter_gambluue.svg")%></div>
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/hewlett_packard_enterprise.svg")%></div>
      <div class="img-tag"><%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/att.svg")%></div>
    </div>
  </div>
</div>
<%# Add Top courses %>
<div class="container">
  <div class="">
    <h1>A broad selection of courses</h1>
  </div>
  <div>
    Choose from over 210,000 online video courses with new additions published every month
  </div>
  <div class="course-list ">
    <ul>
      <% top_courses().each do |course|%>
        <li class="top-course"><a class="row title" href="/selected/<%= course %>"><b><%= course %></b></a></li>
      <%end%>
    </ul>
  </div>
  <div class="show-course">
    <div>
      <div class="course-explore">
        <h1>
          Expand your career opportunities with Python
        </h1>
        <span>
          Take one of Udemy’s range of Python courses and learn how to code using this incredibly useful language. Its simple syntax and readability makes Python perfect for Flask, Django, data science, and machine learning. You’ll learn how to build everything from games to sites to apps. 
          Choose from a range of courses that will appeal to
        </span>
        <div><button >Explore Python</button></div>
      </div>
      <section class="swiper mySwiper" >
        <% if @courses %>
          <div class=" swiper-wrapper card-crousel" id="mySwiper1">
            <% @courses.each do |course|%>
              <div class="card swiper-slide" id="no-border">
                <div class="course-img" id="border"><% if course.course_image.attached? %>
                    <img src=<%=(url_for(course.course_image))%>>
                  <% end %>
                </div>
                <div class="text">
                  <% if  @student_id %>
                    <h3 class="h1-line"><%= link_to "#{course.courseTitle}", course_show_path(student_id: @student_id, course_id: course.id)%></h3>
                  <%else %>
                    <a class="row title" href="/courses/<%= course.id %>">
                      <h5 class="h1-line"><%= course.courseTitle %></h5>
                    </a>
                  <%end%>
                  <div class="row" >
                    <p class="article p-margin"><%= course.courseDescription %></p>
                    <p class="p-margin">Module- <%= course.courseDuration %></p>
                    <p class="p-margin"><b>&#x20B9;<%= course.coursePrice %></b></p>
                    <%= button_to "Buy Now", course_buy_path(student_id: @student_id,course_id: course.id), class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            <%end%>
          </div>
        <% end %>
        <div class="swiper-button-next swiper-btn"></div>
        <div class="swiper-button-prev swiper-btn"></div>
      </section>
    </div>
  </div>
</div>
<%# Add top rated feddbacks of some learners... %>
<div class="feedback-section">
  <div class="container">
    <div >
      <h2>How learners like you are achieving their goals</h2>
    </div>
    <div class="feedback-card">
      <div class= "card card-gap">
        <div class="">
          <i class="fa-solid fa-quote-left"></i>
        </div>
        <div class="">
          To stay at the leading edge of IT innovation, your team needs to regularly reinvent its skillset. With Udemy Business, I can give my team the space to learn and take the initiative. It means we can produce higher quality work more quickly.
        </div>
        <div class="feedback-text ">
          <p class="">I am proud to say that after a few months of taking this course...I passed my exam and am now an AWS Certified Cloud Practitioner! This content was exactly what the CCP exam covered.</p>
        </div>
        <div class="">
          Aman
        </div>
      </div>
      <div class= "card card-gap">
        <div class="">
          <i class="fa-solid fa-quote-left"></i>
        </div>
        <div class="feedback-text">
          <p >I am proud to say that after a few months of taking this course...I passed my exam and am now an AWS Certified Cloud Practitioner! This content was exactly what the CCP exam covered.</p>
        </div>
        <div class="">
          Vishal
        </div>
      </div>
      <div class= "card card-gap">
        <div class="">
          <i class="fa-solid fa-quote-left"></i>
        </div>
        <div class="feedback-text">
          <p>I am proud to say that after a few months of taking this course...I passed my exam and am now an AWS Certified Cloud Practitioner! This content was exactly what the CCP exam covered.</p>
        </div>
        <div class="">
          Shubham
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div>
    <h1>Learners are viewing</h1>
  </div>
  <section class="swiper mySwiper" id='swiper'>
    <div class=" swiper-wrapper card-crousel">
      <% @course.each do |course|%>
        <div class="card swiper-slide" id="no-border">
          <div class="course-img" id="border"> <% if course.course_image.attached? %>
              <img src=<%=(url_for(course.course_image))%>>
            <% end %>
          </div>
          <div class="text">
            <% if  @student_id %>
              <h3><%= link_to "#{course.courseTitle}", course_show_path(student_id: @student_id, course_id: course.id)%></h3>
            <%else %>
              <a class="row title" href="/courses/<%= course.id %>">
                <h3><%= course.courseTitle %></h3>
              </a>
            <%end%>
            <div class="row">
              <p class="article"><%= course.courseDescription %></p>
            </div>
          </div>
        </div>
      <%end%>
    </div>
    <div class="swiper-button-next swiper-btn"></div>
    <div class="swiper-button-prev swiper-btn"></div>
  </section>
</div>
<%# Add all top category-wise skills %>
<div class="container categories">
  <div>
    <h1>Top Caterogies</h1>
  </div>
  <div class="row ">
    <div class="col-3 category-card">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-design-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Design</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-personal-development-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Development</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-marketing-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Marketing</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-it-and-software-2x-v2.jpg")%></div>
      <div class="text">
        <h5>IT & Software</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-design-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Personal Development</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-business-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Business</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-photography-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Photography</h5>
      </div>
    </div>
    <div class="col-3 ">
      <div class="category-img"><%= image_tag("https://s.udemycdn.com/home/top-categories/lohp-category-music-2x-v2.jpg")%></div>
      <div class="text">
        <h5>Add new category</h5>
      </div>
    </div>
  </div>
</div>
<%# Adding Category and it's related courses assigned.... %>
<div class="category-div">
  <div class="container">
    <h1>Featured topics by category</h1>
    <div class=" category-list" >
      <% Category.all.map do |category|%>
        <div class="course-title">
          <h4><%= category.category_title %></h4>
          <div>
            <% category.courses.map do |course|%>
              <h5><%= link_to course.courseTitle %></h5>
            <%end%>
          </div>
        </div>
      <%end%>
    </div>
    <button class="moretopics-btn">Explore more topics</button>
  </div>
</div>
<%# Add business section %>
<div class="business container">
  <div class="sub-business">
    <div class="business-text">
      <h3>Udemy Business</h3>
      <h1>Upskill your team with Udemy Business</h1>
      <ul>
        <li>Unlimited access to 22,000+ top Udemy courses, anytime, anywhere</li>
        <li>International course collection in 14 languages</li>
        <li>Top certifications in tech and business</li>
      </ul>
      <div>
        <button class="moretopics-btn" id="explore-more">Get Udemy Business</button>
        <button class="moretopics-btn">Learn More</button>
      </div>
    </div>
    <div class="business-img"><%= image_tag("https://s.udemycdn.com/home/non-student-cta/UB_Promo_1200x1200.jpg")%></div>
  </div>
</div>
<%# Add customers stories %>
<div class="category-div" id="customer-div">
  <div class="customer-story container">
    <div class=" customer" id="story" >
      <div class=" customer-text" >
        <i class="fa-solid fa-quote-left"></i>
        <p>To stay at the leading edge of IT innovation, your team needs to regularly reinvent its skillset. With Udemy Business, I can give my team the space to learn and take the initiative. It means we can produce higher quality work more quickly.</p>
        <%= link_to "Read full story"%>
      </div>
      <div class=" customer-profile" >
        <div class="profile-img"><%= image_tag("https://s.udemycdn.com/home/ub-case-studies/Ismaeel_Ameen.png")%></div>
        <div class="profile-text">
          <h5><b>Ismaeel Ameen</b></h5>
          <p>Head of Data Engineering</p>
          <p>Development and Data Management</p>
        </div>
        <div>Robert Walters</div>
      </div>
    </div>
  </div>
</div>
<%# Add an intructor %>
<div class="customer-story container">
  <div class=" customer" id="instruct">
    <div class=" customer-profile" >
      <div class="instruct-img"><%= image_tag("https://s.udemycdn.com/home/non-student-cta/instructor-2x-v3.jpg")%></div>
    </div>
    <div class=" customer-text" >
      <h1 class="">Become an instructor</h1>
      <p>Instructors from around the world teach millions of learners on Udemy. We provide the tools and skills to teach what you love.</p>
      <button class="moretopics-btn" id="explore-more">Start teaching today</button>
    </div>
  </div>
</div>
<%= javascript_include_tag("landing_page.js")%>

app/views/students/new.html.erb
<%= render partial: "shared/nav"%>
<div class="nav">
  <h1>Hello, Student</h1>
  <ul>
    <% if student_signed_in? %>
      <li><%= button_to "Sign Out", destroy_student_session_path, method: :delete, class: "btn btn-primary" %></li>
    <% else%>
      <li>
        <h2><%= link_to "Sign In", new_student_session_path%></h2>
      </li>
    <%end%>
  </ul>
</div>
<%= render partial: "form", locals: {student: @student, url: student_create_path, method: nil}%>

app/views/students/show.html.erb
<%= stylesheet_link_tag('student_show') %>


<div class="nav">
  <h1>Student-<%=@student.id%></h1>
  <div class="edit-section">
    <h4 class="edit"><%= link_to "Home", student_index_path%></h4>
    <h4 class="edit"><%= link_to "Edit", student_edit_path%></h4>
    <h4 class="edit"><%= link_to "Delete",  student_delete_path(@student), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></h4>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <%# <div class="row image"> %>
    <%# <% if blog.image.attached? %>
    <%# <img src=<%=(url_for(blog.image))> %>
    <%# <% end %>
    <%# </div> %>
    <div class="text">
      <a class="row title" href="/student/<%= @student.id %>">
        <h3><%= @student.studFName %></h3>
      </a>
      <div class="row">
        <p class="article"> <%= @student.studFName %> <%= @student.studMName %> <%= @student.studLName %></p>
        <p class="">Address- <%= @student.studAddressCity%></p>
        <p class="">Gender- <%= @student.studGender%></p>
        <p class="">Phone Number- <%= @student.studPhone%></p>
        <p class="">Admission Year- <%= @student.yearOfEnroll%></p>
      </div>
    </div>
  </div>
</div>

app/views/students/student_courses.html.erb
<%= stylesheet_link_tag('student_index') %>
<div class="nav">
  <h1><%= @student.studFName%></h1>
  <h4><%= link_to "Back", student_index_path%></h4>
</div>
<div class="row">
  <% @all_courses.each do |course|%>
    <div class="col-3 card">
      <div class="text">
        <% if  @student_id %>
          <h3><%= link_to "#{course.courseTitle}", course_show_path(student_id: @student_id, course_id: course.id)%></h3>
        <%else %>
          <a class="row title" href="/course/<%= course.id %>">
            <h3><%= course.courseTitle %></h3>
          </a>
        <%end%>
        <div class="row">
          <p class="article"><%= course.courseDescription %></p>
          <p class="article">Module- <%= course.courseDuration %></p>
        </div>
        <% if @student.id %>
            <h4 class="edit"><%= link_to "Remove",  student_delete_course_path(student_id: @student.id, course_id: course.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></h4>
        <%end%>
      </div>
    </div>
  <%end%>
</div>