config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "students#landing_page"
  # root to: "devise/sessions#new"
  get "/selected/:choose_course", to: "students#landing_page"
  get "/student/new", to: "students#new"
  get "/student/index", to: "students#index"
  post "/student/create", to: "students#create"
  get "/student/:id", to: "students#show", as: "student_show"
  get "/student/:id/edit", to: "students#edit", as: "student_edit"
  put "/student/:id/update", to: "students#update", as: "student_update"
  delete "/student/:id", to: "students#destroy", as: "student_delete"

  # Routes for Course Model
  # get "/course/new", to: "courses#new"
  # get "/course/index", to: "courses#index"
  # post "/course/create", to: "courses#create"
  # get "/course/:id", to: "courses#show", as: "course_show"
  # get "/course/:id/edit", to: "courses#edit", as: "course_edit"
  # put "/course/:id/update", to: "courses#update", as: "course_update"
  # delete "/course/:id", to: "courses#destroy", as: "course_delete"

  #Association Routes
  get "/student/:id/course/index", to: "courses#index", as: "student_id_course_index"
  post "course_buy", to: "courses#course_buy"
  get "/student/:id/courses", to: "students#student_courses", as: "student_courses"
  delete "/student/:id/courses", to: "students#student_delete_course", as: "student_delete_course"

  resources :courses do
    resources :payments, only: [:show, :index, :new, :create]  # Nest payments under courses
  end

  resources :lectures

  # resources :payments

  resources :contents

  resources :categories
  
  # root "home#index"

  # Defines the root path route ("/")
  # root "articles#index"
  get "/*path", to: "homes#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/views/shared/_course_card.html.erb
<div class="card-container">
  <div class="card-img">
    <%= image_tag(url_for(@course.course_image))%>
  </div>
  <div class="card-user p-all-2">
    <div><b>Personal</b></div>
    <div><b>Teams</b></div>
  </div>
  <div class="course-price-details">
    <div class="course-amount">
      <div id="price-tag"><b>&#x20B9; <%=@course.coursePrice%></b></div>
      <div><s>&#x20B9; 3,199</s></div>
      <div>86% off</div>
    </div>
    <div class="course-buy-tag">
      <button class="buy-course-btn p-1" type="button">
      <% if courses_payment(@course) %>
        <%= link_to "Buy this course", new_course_payment_path(@course), class: "buy-section" %>
      <%else %>
        <%= link_to "Go to the course", "#{root_url}#{@course.id}/lecture", class: "buy-section" %>  
      <%end%>
      </button>
      <button class="like-btn p-1" type="button"><i class="fa-regular fa-heart"></i></button>
    </div>
    <div class="refund-challenge p-1">
      <p>30-Day Money-Back Guarantee</p>
      <p>Full Lifetime Access</p>
    </div>
    <div class="refferal-link">
      <%= link_to "Share"%>
      <%= link_to "Gift this"%>
      <%= link_to "Apply Cupon"%>
    </div>
    <span class="or p-2">or</span>
    <h5> Subscribe to Udemy’s top courses</h5>
    <p>Get this course, plus 10,500+ of our top-rated courses, with Personal Plan. <%= link_to "Learn more"%></p>
    <div class=""> <button class="subscription-btn p-1" type="button">Start subscription</button></div>
    <div class="refund-challenge p-1">
      <p>Starting at ₹750 per month</p>
      <p>Cancle anytime</p>
    </div>
  </div>
</div>

app/views/shared/_filter_course.html.erb
 <%# <% filter_course(${clicked_course}).each do |course|%>  
 <% filter_course("python").each do |course|%> 
      <div class="card swiper-slide">
        <div class="course-img"> <% if course.course_image.attached? %>
            <img src=<%=(url_for(course.course_image))%>>
          <% end %>
        </div>
        <div class="text">
          <% if  @student_id %>
            <h3><%= link_to "#{course.courseTitle}", course_show_path(student_id: @student_id, course_id: course.id)%></h3>
          <%else %>
            <a class="row title" href="/course/<%= course.id %>">
              <h3><%= course.courseTitle %></h3>
            </a>
          <%end%>
          <div class="row">
            <p class="article"><%= course.courseDescription %></p>
            <p class="article">Module- <%= course.courseDuration %></p>
            <p class="article">Price- <%= course.coursePrice %></p>
            <%= button_to "Buy Now", course_buy_path(student_id: @student_id,course_id: course.id), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <%end%>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-info col-3 z-index-4 " id="myNotice" role="alert">
 <%= flash[:notice]%>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-danger col-3 z-index-4"  id="myAlert" role="alert">
 <%= flash[:alert]%>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="sub-footer">
    <div class="footer-element">
      <ul>
        <li><%= link_to "Udemy Business"%></li>
        <li><%= link_to "Tech on udemy"%></li>
        <li><%= link_to "Get the app"%></li>
        <li><%= link_to "About Us"%></li>
        <li><%= link_to "Contact Us"%></li>
      </ul>
      <ul>
        <li><%= link_to "Career"%></li>
        <li><%= link_to "Blog"%></li>
        <li><%= link_to "Helo & Support"%></li>
        <li><%= link_to "Affliate"%></li>
        <li><%= link_to "Investors"%></li>
      </ul>
      <ul>
        <li><%= link_to "Terms"%></li>
        <li><%= link_to "Privacy policy"%></li>
        <li><%= link_to "Cookie"%></li>
        <li><%= link_to "Sitemap"%></li>
        <li><%= link_to "Accessibility statement"%></li>
      </ul>
    </div>
    <div> <button class="moretopics-btn" id="explore-more"><i class="fa-solid fa-globe"></i> English</button></div>
  </div>
</div>

app/views/shared/_nav.html.erb
<%= stylesheet_link_tag('nav') %>
<nav class= "nav-bar">
    <div><h2><%= link_to "Vishal", root_path,  class: "logo-section" %></h2></div>
    <div>
        <a class = "a-tag" href="#">Category</a>
    </div>
    <div class="search-bar">
        <form action="#" class="search-form">
             <button type="submit" disabled class="" tabindex="-1"><i class="fa-solid fa-magnifying-glass"></i></button>
             <input type="text" id="fname" name="fname" placeholder="Search">
        </form>
    </div>
    <div class="business-link " >
        <a class = "a-tag cb" href="#">Course Bussiness</a>
        <a class = "a-tag" href="#">Tech on Website</a>
    </div>
    <div class="login-bar">
        <%# <button class="login-btn">Login </button> %>
        <button class="login-btn"> 
        <% if student_signed_in? %>
          <%= link_to "Sign Out",  destroy_student_session_path, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure? Want to Sign Out!"
                  }, class:"nav-link active" %>
        <% else%>
          <%= link_to "Sign In", new_student_session_path, class:"nav-link active"%>
        <%end%>
        </button>
        <button class="web-btn"> <i class="fa-solid fa-globe"></i></button>
    </div>
</nav>

app/views/shared/_sidebar.html.erb
 <%= stylesheet_link_tag('landing_page') %>
<div class="side-bar">
  <div class="area"></div>
  <nav class="main-menu">
    <ul>
      <li>
        <% if student_signed_in? %>
          <a class="" href="/student/<%= current_student.id %>">
            <% if current_student.profile_image.attached? %>
              <img src=<%=(url_for(current_student.profile_image))%>>
            <% end %>
            <span class="nav-text">
              <%= current_student.studFName %>
            </span>
          </a>
        <%end%>
      </li>
      <li class="has-subnav">
        <% if student_signed_in? %>
          <a class="link-opacity-100" href="/student/<%= current_student.id %>/course/index">
            <i class="fa fa-book fa-2x"></i>
            <span class="nav-text">
              Buy course
            </span>
          </a>
        <%end%>
      </li>
      <li class="has-subnav">
        <% if student_signed_in? %>
          <a class="link-opacity-100" href="/student/<%= current_student.id %>/courses">
            <i class="fa fa-bookmark fa-2x"></i>
            <span class="nav-text">
              My courses
            </span>
          </a>
        <%end%>
      </li>
    </ul>
    <% if student_signed_in? %>
      <ul class="logout">
        <li>
          <a href="#">
            <i class="fa fa-power-off fa-2x"></i>
            <span class="nav-text">
              <%= link_to "Sign Out",  destroy_student_session_path, data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure? Want to Sign Out!"
                        } %>
            </span>
          </a>
        </li>
      </ul>
    <% end%>
  </nav>
</div>