config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "students#landing_page"
  # root to: "devise/sessions#new"
  get "/selected/:choose_course", to: "students#landing_page"
  get "/student/new", to: "students#new"
  get "/student/index", to: "students#index"
  post "/student/create", to: "students#create"
  get "/student/:id", to: "students#show", as: "student_show"
  get "/student/:id/edit", to: "students#edit", as: "student_edit"
  put "/student/:id/update", to: "students#update", as: "student_update"
  delete "/student/:id", to: "students#destroy", as: "student_delete"

  # Routes for Course Model
  # get "/course/new", to: "courses#new"
  # get "/course/index", to: "courses#index"
  # post "/course/create", to: "courses#create"
  # get "/course/:id", to: "courses#show", as: "course_show"
  # get "/course/:id/edit", to: "courses#edit", as: "course_edit"
  # put "/course/:id/update", to: "courses#update", as: "course_update"
  # delete "/course/:id", to: "courses#destroy", as: "course_delete"

  #Association Routes
  get "/student/:id/course/index", to: "courses#index", as: "student_id_course_index"
  post "course_buy", to: "courses#course_buy"
  get "/student/:id/courses", to: "students#student_courses", as: "student_courses"
  delete "/student/:id/courses", to: "students#student_delete_course", as: "student_delete_course"

  resources :courses do
    resources :payments, only: [:show, :index, :new, :create]  # Nest payments under courses
  end

  resources :lectures

  # resources :payments

  resources :contents

  resources :categories
  
  # root "home#index"

  # Defines the root path route ("/")
  # root "articles#index"
  get "/*path", to: "homes#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :course
    belongs_to  :student

    enum status: { pending: 0, paid: 1, failed: 2}
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @course = Course.find(params[:course_id])
  end

  def create
    @course = Course.find(params[:course_id])
    begin
      stripe_customer = StripeService.create_or_retrieve_customer(current_user)
      payment_intent = StripeService.create_payment_intent(current_user, @course)
      
      if payment_intent.status == "succeeded"
        success, @payment = PaymentService.process_payment(@course, current_user, payment_intent)
        if success
          redirect_to root_url, notice: 'Payment was successfully created.'
        else
          render :new, status: :unprocessable_entity
        end
      else
        flash[:error] = 'Payment failed'
        redirect_to root_url, status: :unprocessable_entity
      end
    rescue Stripe::StripeError => e
      flash[:error] = e.message
      redirect_to root_url, status: :unprocessable_entity
    end
  end
      
  def success
    #handle successful payments
    redirect_to root_url, notice: "Purchase Successful"
  end
  
  def cancel
    #handle if the payment is cancelled
    redirect_to root_url, notice: "Purchase Unsuccessful"
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/index.html.erb
<%= stylesheet_link_tag('payments') %>

<div class="payments"> 
<%= form_tag payments_path do %>
  <label class="amount">
      <span>Amount: $5.00</span>
  </label>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="500"
    data-locale="auto">
  </script>
<% end %>
</div>

app/views/payments/new.html.erb
<%= stylesheet_link_tag 'payments' %>

<div class="payments"> 
  <%= form_tag course_payments_path(@course), method: :post do %>
    <label class="amount">
      <span>Amount: $<%= @course.coursePrice %></span>
    </label>

    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="A month's subscription"
      data-amount="<%= (2 * 100).to_i %>" 
      data-currency="usd"
      data-locale="auto">
    </script>
  <% end %>
  

  <script src="https://js.stripe.com/v2/"></script>
  <script>
    Stripe.setPublishableKey("<%= ENV['PUBLIC_KEY'] %>");
  </script>
</div>

app/views/payments/show.html.erb
<div>
Hello
<%= @course.id%>
</div>