config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "students#landing_page"
  # root to: "devise/sessions#new"
  get "/selected/:choose_course", to: "students#landing_page"
  get "/student/new", to: "students#new"
  get "/student/index", to: "students#index"
  post "/student/create", to: "students#create"
  get "/student/:id", to: "students#show", as: "student_show"
  get "/student/:id/edit", to: "students#edit", as: "student_edit"
  put "/student/:id/update", to: "students#update", as: "student_update"
  delete "/student/:id", to: "students#destroy", as: "student_delete"

  # Routes for Course Model
  # get "/course/new", to: "courses#new"
  # get "/course/index", to: "courses#index"
  # post "/course/create", to: "courses#create"
  # get "/course/:id", to: "courses#show", as: "course_show"
  # get "/course/:id/edit", to: "courses#edit", as: "course_edit"
  # put "/course/:id/update", to: "courses#update", as: "course_update"
  # delete "/course/:id", to: "courses#destroy", as: "course_delete"

  #Association Routes
  get "/student/:id/course/index", to: "courses#index", as: "student_id_course_index"
  post "course_buy", to: "courses#course_buy"
  get "/student/:id/courses", to: "students#student_courses", as: "student_courses"
  delete "/student/:id/courses", to: "students#student_delete_course", as: "student_delete_course"

  resources :courses do
    resources :payments, only: [:show, :index, :new, :create]  # Nest payments under courses
  end

  resources :lectures

  # resources :payments

  resources :contents

  resources :categories
  
  # root "home#index"

  # Defines the root path route ("/")
  # root "articles#index"
  get "/*path", to: "homes#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @course = Course.new
  end

  def index
    @student_id = params[:id]
    # @user = Student.find(@student_id)
    @course = Course.all
  end

  def create
    # debugger
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def show
    
    @student_id = params[:student_id]

    if params[:student_id] == params[:id]
      @course = Course.find(params[:course_id])
    else
      @course = Course.find(params[:id])
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params)
      redirect_to course_show_path
    else
      render plain: "student not found!"
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_path
  end

  def course_buy
    if current_student.present?
      @student = Student.find(current_student.id)
      @course = Course.find(params[:course_id])

      # @student.teachers.create(course_id: @course.id)

      @teacher = Teacher.new(course_id: @course.id, student_id: @student.id)
      if @teacher.save
        flash[:notice] = "Course have been assigned"
        redirect_to root_path
      else
        flash[:alert] = "Error"
        redirect_to courses_path
      end
    else
      flash[:alert] = "Login First"
      redirect_to root_path
    end

    #@student = Student.find(params[:student_id])
  end

  def course_content
    
    binding.pry
    
  end

  private

  def course_params
    params.require(:course).permit(:courseTitle, :courseDuration, :courseModule, :courseDescription, :coursePrice, :course_image, :category_id)
  end
end

app/views/courses/_form.html.erb
<%= form_with model: course, url: url, multipart: true, method: method  do |form| %>
  <div class="mb-3">
    <%= form.label "Course Name"%>
    <%= form.text_field :courseTitle, class: "form-control", placeholder: "Course Name"%>
  </div>
  <div class="mb-3">
    <%= form.label "Course Duration"%>
    <%= form.number_field :courseDuration, class: "form-control", placeholder: "Duration"%>
  </div>
  <div class="mb-3">
    <%= form.label "Total Module"%>
    <%= form.number_field :courseModule, class: "form-control", placeholder: "Module"%>
  </div>
  <div class="mb-3">
    <%= form.label "Course Details"%>
    <%= form.text_field :courseDescription, class: "form-control", placeholder: "Description"%>
  </div>
  <div class="mb-3">
    <%= form.label "Course Price"%>
    <%= form.number_field :coursePrice, class: "form-control", placeholder: "Total Price"%>
  </div>
  <div class="mb-3">
        <%= form.label :category_id%>
        <%= form.select :category_id, options_for_select(Category.all.map { |c| [c.category_title, c.id] }), class: "form-control"%>
    </div>
  <div class="mb-3">
    <%= form.label "Upload Image"%>
    <%= form.file_field :course_image, class: "form-control"%>
  </div>
  <div class="mb-3">
    <%= form.submit "ADD", class: "btn btn-primary"%>
  </div>
<%end%>

app/views/courses/edit.html.erb
<h1>Edit Student</h1>

<%= render partial: "form", locals: {course: @course, url: course_update_path, method: :put}%>

app/views/courses/index.html.erb
<%= stylesheet_link_tag('student_index') %>
<div class="nav">
  <h1>Course Dashboard</h1>
  <%if !@student_id%>
    <h4><%= link_to "Add New Course", new_course_path %></h4>
  <%end%>
</div>
<div class="row">
  <% @course.each do |course|%>
    <div class="col-3 card">
      <div class="text">
        <div class="course-header">
          <% if  @student_id %>
            <h3><%= link_to "#{course.courseTitle}", course_show_path(student_id: @student_id, course_id: course.id)%></h3>
          <%else %>
            <a class="row title" href="/course/<%= course.id %>">
              <h3><%= course.courseTitle %></h3>
            </a>
          <%end%>
          <div class="profile-img">
            <% if course.course_image.attached? %>
              <img src=<%=(url_for(course.course_image))%>>
            <% end %>
          </div>
        </div>
        <div class="row">
          <p class="article"><%= course.courseDescription %></p>
          <p class="article">Module- <%= course.courseDuration %></p>
          <% if current_student.is_admin %>
            <%= link_to "Create Content", new_content_path(course_id: course.id), class: "btn btn-primary" %>
          <%else%>
            <%= button_to "Buy Now", course_buy_path(student_id: @student_id,course_id: course.id), class: "btn btn-primary" %>
          <%end%>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/courses/new.html.erb
<h1>Add Courses</h1>

<%= render partial: "form", locals: {course: @course, url: courses_path,  method: nil}%>

app/views/courses/show.html.erb
<%= stylesheet_link_tag('student_show') %>
<%= render partial: "shared/course_card"%>
<div class="top-container">
  <div class="container p-2">
    <div class="category-title">
      <span>Development 	&gt; Web Development 	&gt; Web Development </span> <span></span>
    </div>
    <div class="course-title">
      <h1><%=@course.courseTitle%></h1>
      <p>Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps</p>
    </div>  
    <div class="course-overview ">
      <span class="bestseller">Bestseller</span>
      <span class="course-rating">4.7 &#9733; &#9733; &#9733; &#9733;</span>
      <span class="voilet">(330,238 ratings)</span>
      <span class="w">1,099,376 students</span>
    </div>
    <div class="course-overview p-2">
      <span class="w">Created by <a  class="voilet" href="#">Dr. Angele Yu</a></span>
    </div>
    <div class="course-overview" id="overview-gap">
      <span class="w"><i class="fa-regular fa-star"></i> &nbsp; Last updated 10/2023</span>
      <span class="w"><i class="fa-solid fa-globe"></i> &nbsp; English</span>
      <span class="w"><i class="fa-solid fa-keyboard"></i> &nbsp; 1,099,376 English [Auto], Arabic [Auto], <a  class="voilet" href="#">more</a></span>
    </div>
  </div>
</div>
<div class="container">
  <div class="what-you-learn m-4 p-2">
    <h2>What you'll learn</h2>
    <div class="summary-texts">
      <div>
        <div class="summary-text">
          <span>&check;</span>
          <p>Build 16 web development projects for your portfolio, ready to apply for junior developer jobs.</p>
        </div>
        <div class="summary-text"><span>&check;</span>
          <p>After the course you will be able to build ANY website you want.</p>
        </div>
        <div class="summary-text"><span>&check;</span>
          <p>Work as a freelance web developer.</p>
        </div>
        <div class="summary-text"><span>&check;</span>
          <p>Master backend development with Node.</p>
        </div>
      </div>
      <div>
        <div class="summary-text"> <span>&check;</span>
          <p>Build 16 web development projects for your portfolio, ready to apply for junior developer jobs.</p>
        </div>
        <div class="summary-text"><span>&check;</span>
          <p>After the course you will be able to build ANY website you want.</p>
        </div>
        <div class="summary-text"><span>&check;</span>
          <p>Work as a freelance web developer.</p>
        </div>
        <div class="summary-text"><span>&check;</span>
          <p>Master backend development with Node.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="course-include m-4 p-2">
    <h2>This course includes:</h2>
    <div class="course-include-texts">
      <div>
        <div class="summary-text">
          <%= image_tag("youtube.svg")%>
          <p>62.5 hours on-demand video</p>
        </div>
        <div class="summary-text">
         <%= image_tag("lrarrow.svg")%>
          <p>7 coding exercises</p>
        </div>
        <div class="summary-text">
         <%= image_tag("file.svg")%>
          <p>70 articles</p>
        </div>
      </div>
      <div>
        <div class="summary-text">
          <%= image_tag("folder.svg")%>
          <p>110 downloadable resources</p>
        </div>
        <div class="summary-text">
        <%= image_tag("mobile.svg")%>
          <p>Access on mobile and TV</p>
        </div>
        <div class="summary-text">
         <%= image_tag("worldcup.svg")%>
          <p>Certificate of completion</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="what-you-learn m-4 p-2">
    <div>
      <h4>Top companies offer this course to their employees</h4>
      <p>This course was selected for our collection of top-rated courses trusted by businesses worldwide. Learn more</p>
    </div>
    <div class="summary-logo">
      <div>
        <%= image_tag("https://s.udemycdn.com/partner-logos/v4/nasdaq-dark.svg")%>
      </div>
      <div>
        <%= image_tag("https://s.udemycdn.com/partner-logos/ou-v1/volkswagen.svg")%>
      </div>
      <div>
        <%= image_tag("https://s.udemycdn.com/partner-logos/v4/box-dark.svg")%>
      </div>
      <div>
        <%= image_tag("https://s.udemycdn.com/partner-logos/v4/netapp-dark.svg")%>
      </div>
      <div>
        <%= image_tag("https://s.udemycdn.com/partner-logos/v4/eventbrite-dark.svg")%>
      </div>
    </div>
  </div>
</div>
<div class="container ">
  <div class=" coding-exercises p-all-4">
    <div class="coding-exercises-text">
      <h1>Coding Exercises</h1>
      <p>This course includes our updated coding exercises so you can practice your skills as you learn.</p>
      <%= link_to "See a demo"%>
    </div>
    <div class="coding-exercises-img">
      <div class=""><%= image_tag(url_for(@course.course_image))%></div>
    </div>
  </div>
</div>
<div class="container">
  <h1>Course Content</h1>
</div>
<div class="container ">
  <div class="content-count">
    <p>47 sections • 398 lectures • 63h 5m total length</p>
    <p>Expand all sections</p>
  </div>
  <div class="width-75">
    <% @course.contents.each do |content| %>
      <div class="content-bar" data-content-id="<%= content.id %>">
        <div class="content-bar-header">
          <div class="content-topic">
            <i class="fa-solid fa-chevron-down"></i>
            <span><b><%= content.content_title %></b></span>
          </div>
          <div class="content-duration">
            <div>9 lectures &middot; 37 min</div>
          </div>
        </div> 
        <div class="content-details hidden" id="content-details-<%= content.id %>">
          <ul>
            <% content.lectures.each do |lecture| %>
              <li class="list-style"><%= lecture.lecture_title %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%# Card Container %>

<%= javascript_include_tag("course_page.js")%>